### ISSUE TITLE
Great Job!

### ISSUE THREAD

**Issue by wilfriedcoffiea** [cubiclesoft/sso-client-php#1]
### 👋 Hi Guy/Guys and All the team of Cubiclesoft !
Above all, I want to thank you for all your great work.
What you did with the SSO Server is just great.
However I have a problem when I try to install the SSO Client PHP.
There is an error message that occurs like you can see on this shared picture.
Could you help please?
Thank you in advance.
![screencapture-sso-client-install-php](https://user-images.githubusercontent.com/20947891/62095061-c4d5bf80-b26e-11e9-8a1a-5747e73c55af.jpg)

**Comment by cubiclesoft** [comment]
Does the "sso-server" domain have a configured SSL certificate?  If it does, you'll need to add the CA's root public certificate to the `support/cacert.pem` file (or just replace the file with your root CA public cert).  The client probably can't connect since it can't valid the SSL certificate.

**Comment by cubiclesoft** [comment]
By the way, you shouldn't publish API keys and secrets to the Internet.  I'll assume this is just a test setup.  :)

**Comment by wilfriedcoffiea** [comment]
Thanks a lot @cubiclesoft, everything works like a charm!
And yes thanks also for remembering me advice about using API keys and secrets to the Internet :)
